# Generated by Django 5.0 on 2024-10-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationmessage',
            options={'ordering': ('-created_at',)},
        ),
    ]
